name: Rebuild Cache

on:
  # Trigger manually from GitHub UI
  workflow_dispatch:

  # Trigger when events.csv or geometries are updated
  push:
    branches:
      - main
    paths:
      - 'events.csv'
      - 'geometries/**'

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Rebuild cache
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: node rebuild-cache.js
