name: Rebuild Cache

on:
  # Trigger manually from GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

  # Trigger when events.csv or geometries are updated
  push:
    branches:
      - main
      - staging
    paths:
      - 'events.csv'
      - 'geometries/**'

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment
        id: env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "STAGING=${{ github.event.inputs.environment == 'staging' && 'true' || 'false' }}" >> $GITHUB_OUTPUT
            echo "ENV_NAME=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "STAGING=true" >> $GITHUB_OUTPUT
            echo "ENV_NAME=staging" >> $GITHUB_OUTPUT
          else
            echo "STAGING=false" >> $GITHUB_OUTPUT
            echo "ENV_NAME=production" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Import CSV to database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          STAGING: ${{ steps.env.outputs.STAGING }}
        run: |
          echo "Importing events.csv to ${{ steps.env.outputs.ENV_NAME }} database..."
          node .dev/import-csv.js

      - name: Rebuild cache
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          STAGING: ${{ steps.env.outputs.STAGING }}
        run: |
          echo "Rebuilding ${{ steps.env.outputs.ENV_NAME }} cache..."
          node .dev/rebuild-cache.js
